pipeline {
  agent {
    kubernetes {
      cloud 'terralogic-eks-agent'
      inheritFrom 'jenkins-kaniko-agent'
      defaultContainer 'jnlp'
    }
  }

  options {
    durabilityHint('PERFORMANCE_OPTIMIZED')
    disableConcurrentBuilds()
    timeout(time: 1, unit: 'HOURS')
    skipDefaultCheckout(true)
  }

  environment {
    MAVEN_REPO = 'maven-repo'
    MVN_CACHE_NAME = 'mvn-cache'
  }

  stages {

    /* ================= CHECKOUT ================= */
    stage('Checkout') {
      when {
        not { triggeredBy 'BranchIndexingCause' }
      }
      steps {
        checkout scm
        sh 'mvn -version'
      }
    }

    /* ================= RESTORE MAVEN CACHE ================= */
    stage('Restore Maven Cache') {
      when {
        not { triggeredBy 'BranchIndexingCause' }
      }
      steps {
        sh "mkdir -p ${MAVEN_REPO}"
        readCache name: "${MVN_CACHE_NAME}"
      }
    }

    /* ================= MAVEN BUILD ================= */
    stage('Maven Build') {
      when {
        not { triggeredBy 'BranchIndexingCause' }
      }
      steps {
        sh """
          mvn clean install \
            -Dmaven.repo.local=${MAVEN_REPO} \
            -DskipTests
        """
      }
    }

    /* ================= SAVE MAVEN CACHE ================= */
    stage('Save Maven Cache') {
      when {
        not { triggeredBy 'BranchIndexingCause' }
      }
      steps {
        writeCache(
          name: "${MVN_CACHE_NAME}",
          includes: "${MAVEN_REPO}/**"
        )
      }
    }
  }

  post {
    success {
      echo "Maven build SUCCESS on ${env.BRANCH_NAME}"
    }
    failure {
      echo "Maven build FAILED on ${env.BRANCH_NAME}"
    }
  }
}

