pipeline {
  agent {
    kubernetes {
      cloud 'terralogic-eks-agent'
      inheritFrom 'jenkins-kaniko-agent'
      defaultContainer 'jnlp'
    }
  }

  options {
    disableConcurrentBuilds()
    timeout(time: 30, unit: 'MINUTES')
    durabilityHint('PERFORMANCE_OPTIMIZED')
  }

  environment {
    MAVEN_REPO = 'maven-repo'
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
        sh 'mvn -version'
      }
    }

    stage('Maven Build') {
      steps {
        sh """
          mvn clean install \
            -Dmaven.repo.local=${MAVEN_REPO} \
            -DskipTests
        """
      }
    }
  }

  post {
    success {
      echo "Maven build SUCCESS on branch ${env.BRANCH_NAME}"
    }
    failure {
      echo "Maven build FAILED on branch ${env.BRANCH_NAME}"
    }
  }
}
